{% set name = "streamlit" %}
{% set version = "0.44.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../lib/dist

build:
  noarch: python
  # This number should go up if the conda files change but the wheel
  # file stays the same.
  number: 0
  script: |
    pip install streamlit-{{ version }}-py2.py3-none-any.whl

requirements:
  build:
    - python

  run:
    - python
    # TODO(armando): Make this list automatic.
    # This is just a copy of the python3 dependencies from lib/Pipfile
    # with the exception of purposely not including watchdog.
    - base58
    - blinker
    - botocore
    - boto3
    - click
    - docutils
    - entrypoints
    - enum-compat
    - future
    - numpy
    - pandas
    - pillow
    - protobuf
    - psutil
    - pydot
    - seaborn
    - tensorflow
    - toml
    - tornado
    - tzlocal

about:
  home: https://streamlit.io
  summary: A stateless alternative to Jupyter notebooks for machine learning and data science.
  doc_url: https:/streamlit.io/secret/docs
