# Has to be 2.3 in order o to use runtime: nvidia
version: '2.3'

services:
  streamlit:
    image: streamlit/streamlit:${STREAMLIT_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        STREAMLIT_VERSION: ${STREAMLIT_VERSION}

  streamlit-gpu:
    image: streamlit/streamlit:${STREAMLIT_VERSION}-gpu
    build:
      context: .
      dockerfile: Dockerfile.gpu
      args:
        STREAMLIT_VERSION: ${STREAMLIT_VERSION}

  # Copy wheel to wheel/ directory, uncomment streamlit-wheel, run these commands
  #   (cd docker/aws; docker-compose build streamlit-wheel)
  #   (cd docker/aws; docker push streamlit/streamlit:my_wheel)
  #
  #streamlit-wheel:
  #  image: streamlit/streamlit:my_wheel
  #  build:
  #    context: wheel
  #    dockerfile: Dockerfile

  streamlit-examples:
    image: streamlit/streamlit:examples-${STREAMLIT_VERSION}
    build:
      context: ../../examples
      dockerfile: Dockerfile
      args:
        STREAMLIT_VERSION: ${STREAMLIT_VERSION}

  streamlit-examples-images:
    image: streamlit/streamlit:examples-${STREAMLIT_VERSION}
    command: /examples/images.py
    ports:
      - 5600:8501

  streamlit-examples-reference:
    image: streamlit/streamlit:examples-${STREAMLIT_VERSION}
    command: /examples/reference.py
    ports:
      - 5601:8501

  streamlit-examples-mnist:
    image: streamlit/streamlit:mnist-${STREAMLIT_VERSION}
    build:
      context: ../../examples
      dockerfile: Dockerfile.mnist
      args:
        STREAMLIT_VERSION: ${STREAMLIT_VERSION}
    ports:
      - 5602:8501

  streamlit-examples-mnist-gpu:
    image: streamlit/streamlit:mnist-${STREAMLIT_VERSION}-gpu
    runtime: nvidia
    build:
      context: ../../examples
      dockerfile: Dockerfile.mnist.gpu
      args:
        STREAMLIT_VERSION: ${STREAMLIT_VERSION}
    ports:
      - 5652:8501
