groups:
  - name: process_slave_1s
    interval: 1s

    rules:
    - record: instance:process_cpu_seconds:rate1m
      expr: rate(process_cpu_seconds_total[1m])

  - name: process_master_1s
    interval: 1s
    rules:
    # up
    - record: job:up:count
      expr: count(up) by (job)

    - record: job:up:sum
      expr: sum(up) by (job)

    # process_cpu_seconds_total
    - record: job:process_cpu_seconds:max_rate1m
      expr: max(instance:process_cpu_seconds:rate1m) by (job)
    - record: job:process_cpu_seconds:min_rate1m
      expr: min(instance:process_cpu_seconds:rate1m) by (job)
    - record: job:process_cpu_seconds:median_rate1m
      expr: quantile(0.5, instance:process_cpu_seconds:rate1m) by (job)

    # process_resident_memory_bytes
    - record: job:process_resident_memory_bytes:max
      expr: max(process_resident_memory_bytes) by (job)
    - record: job:process_resident_memory_bytes:min
      expr: min(process_resident_memory_bytes) by (job)
    - record: job:process_resident_memory_bytes:median
      expr: quantile(0.5, process_resident_memory_bytes) by (job)

    # process_virtual_memory_bytes
    - record: job:process_virtual_memory_bytes:max
      expr: max(process_virtual_memory_bytes) by (job)
    - record: job:process_virtual_memory_bytes:min
      expr: min(process_virtual_memory_bytes) by (job)
    - record: job:process_virtual_memory_bytes:median
      expr: quantile(0.5, process_virtual_memory_bytes) by (job)

    # process_open_fds
    - record: job:process_open_fds:max
      expr: max(process_open_fds) by (job)
    - record: job:process_open_fds:min
      expr: min(process_open_fds) by (job)
    - record: job:process_open_fds:median
      expr: quantile(0.5, process_open_fds) by (job)

    # process_max_fds
    - record: job:process_max_fds:max
      expr: max(process_max_fds) by (job)
    - record: job:process_max_fds:min
      expr: min(process_max_fds) by (job)
    - record: job:process_max_fds:median
      expr: quantile(0.5, process_max_fds) by (job)

    # process_start_time_seconds
    - record: job:process_start_time_seconds:max
      expr: max(process_start_time_seconds) by (job)
    - record: job:process_start_time_seconds:min
      expr: min(process_start_time_seconds) by (job)
    - record: job:process_start_time_seconds:median
      expr: quantile(0.5, process_start_time_seconds) by (job)
